Support configuring when to evict based on SQL exceptions, states, codes
brettwooldridge/HikariCP pull request #1509
Opened 2019-12-04 23:14 UTC by westse

Addresses https://github.com/brettwooldridge/HikariCP/issues/1489 by allowing users to configure the SQL exceptions/states/codes that will result in eviction.

2020-01-13 16:48 UTC, rareddy commented
Can this PR be reviewed merged? we are running into this also it would nice to have this fixed ;)

2020-01-13 18:02 UTC, johnou requested changes

2020-01-13 18:02 UTC, johnou commented on src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java
> +   private ConnectionEvictionConfig connectionEvictionConfig;
final

2020-01-13 18:04 UTC, johnou commented on src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java
> +         if (sqlState != null && connectionEvictionConfig.getTerminalErrorStatePrefixes().stream().anyMatch(sqlState::startsWith)
Does this method still inline?

2020-01-14 00:11 UTC, westse commented on src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java
> +         if (sqlState != null && connectionEvictionConfig.getTerminalErrorStatePrefixes().stream().anyMatch(sqlState::startsWith)
Sorry, what do you mean by "inline"?

2020-01-14 21:53 UTC, westse commented
For what its worth, https://github.com/brettwooldridge/HikariCP/issues/1489#issuecomment-574390990 contains a workaround until this PR or another gets merged.

2020-02-03 14:23 UTC, brettwooldridge commented
See comment [here](https://github.com/brettwooldridge/HikariCP/issues/1489#issuecomment-581437268).

2020-02-03 14:23 UTC, closed without merging

2020-02-03 16:04 UTC, westse commented
Sounds great. Thanks for the fix!